### ISSUE TITLE
Using the Composite functionality, in xarray grided data, but not Landsat

### ISSUE THREAD

**Issue by ricardobarroslourenco** [compgeolab/xlandsat#86]
Hi @leouieda ! I came across the xlandsat example you posted in your webpage (https://www.leouieda.com/blog/rio-grande-do-sul-floods-2024.html ) and was pretty excited by the usability. I wonder if you can help me with an issue.
 
 I was wondering if it is possible to use its composite function to do other ternary RGB maps, but using sources different from landsat. 

I have been dealing with a ternary plot I want to do with xarray and cartopy (https://discourse.pangeo.io/t/issues-while-plotting-a-ternary-map-from-xarray-with-cartopy/4366), but imshow doesn't handle well irregular grids, and pcolormesh gives me some aliasing. I wonder if xlandsat would be a good solution for this, or if you suggest other package. I basically need to plot the gridded rgb (each a xarray array) and geographical boundaries (which I have used Cartopy for).

**Comment by leouieda** [comment]
Hi @ricardobarroslourenco thanks for the feedback. I think it should work as long as you put everything into a Dataset and then provide the variable names to the function. I'm not sure it will help with the aliasing bit since we don't interpolate or do anything like that. You might want to try interpolating the data separately so you can control the aliasing part (filter/reduce the data and then grid on a regular interval). You could use the BlockReduce and nearest neighbors interpolations in [Verde](https://www.fatiando.org/verde/latest/) for that.

**Comment by ricardobarroslourenco** [comment]
Thanks for the suggestion. I have already solved my personal issue (it was a pcolormesh issue, and I have solved changing the interpolator to the scikit-image RGB module). But I will keep an eye on Verde as you mentioned. Thanks again.
